//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLib.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrarySystemEntities : DbContext
    {
        public LibrarySystemEntities()
            : base("name=LibrarySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Job_titles> Job_titles { get; set; }
        public virtual DbSet<Library_catalog> Library_catalog { get; set; }
        public virtual DbSet<List_of_authors> List_of_authors { get; set; }
        public virtual DbSet<Register_of_copies> Register_of_copies { get; set; }
        public virtual DbSet<Registration_list> Registration_list { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
