//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLib.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Library_catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Library_catalog()
        {
            this.List_of_authors = new HashSet<List_of_authors>();
            this.Register_of_copies = new HashSet<Register_of_copies>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> Library_cipher { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Year_of_publication { get; set; }
        public string Place_of_publication { get; set; }
        public string Publishing_house_name { get; set; }
        public int Total { get; set; }
        public int Number_of_available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_of_authors> List_of_authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register_of_copies> Register_of_copies { get; set; }
    }
}
