//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_authors
    {
        public int Library_catalog_Id { get; set; }
        public int Author_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Library_catalog Library_catalog { get; set; }
    }
}
