//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLib.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register_of_copies
    {
        public int Id { get; set; }
        public Nullable<int> Issued_to { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> When_issued { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> When_must_be_returned { get; set; }
        public Nullable<bool> Is_returned { get; set; }
        public Nullable<int> Last_reader { get; set; }
        public Nullable<bool> Fine_paid { get; set; }
        public int Library_catalog_Id { get; set; }
    
        public virtual Library_catalog Library_catalog { get; set; }
        public virtual Registration_list Registration_list { get; set; }
    }
}
